name: CI

on:
  push:
    branches:
      - dev
      - "feature/**"
      - "hotfix/**"
    paths:
      - "src/BuildingBlocks/*"

  pull_request:
    branches:
      - dev
      - master
    paths:
      - "src/BuildingBlocks/**"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - run: dotnet restore
      - run: dotnet build --no-restore -warnaserror
      - run: dotnet test --no-build || echo "No tests found."
